# Generated by Django 4.2.30 on 2026-06-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_load_mock_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicerecord',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoicerecord',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicerecord',
            name='supplier_cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
