# ledger/mock_data.py
# Mock data for the Ledger application

TRANSLATIONS = {
    "en": {
        "nav_dashboard": "Dashboard",
        "nav_invoices": "Invoices",
        "nav_licenses": "Licenses",
        "nav_machines": "Machines",
        "nav_profile": "Profile",
        "btn_new_asset": "New Asset",
        "btn_settings": "Settings",
        "btn_support": "Support",
        "search_placeholder": "Search...",
        "lang_toggle": "Português",
        "dashboard_title": "Strategic Overview",
        "dashboard_subtitle": "Global IT inventory and license compliance status.",
        "btn_generate_report": "Generate Report",
        "btn_export_csv": "Export CSV",
        "card_total_assets": "Total Assets",
        "card_active_licenses": "Active Licenses",
        "card_monthly_spend": "Monthly Spend",
        "section_critical_alerts": "Critical Alerts",
        "section_software_utilization": "Software Utilization by Sector",
        "section_recent_history": "Recent Movement History",
        "view_all": "View all",
        "alerts": [
            {
                "title": "License Compliance Risk",
                "description": "Adobe Creative Cloud licenses exceeded. 142 machines detected vs 120 allocated seats. Potential audit liability: $3,200.",
                "label": "2 issues detected",
                "type": "critical",
            },
            {
                "title": "Expiring Software Contracts",
                "description": "JetBrains Enterprise renewal due in 14 days. Estimated cost: $12,450.",
                "label": "Review Invoice",
                "type": "warning",
            },
        ],
        "history": [
            {"title": "MacBook Pro M3 Provisioned", "subtitle": "Assigned to: Sara Chen (Engineering)", "tag": "ASSET TAG AM-4320", "time": "14 mins ago", "type": "success"},
            {"title": "License Reallocation", "subtitle": "AutoCAD Suite moved from Marketing to R&D pool.", "tag": "SOFT-ASSET", "time": "1 hour ago", "type": "info"},
            {"title": "Decommissioned Hardware", "subtitle": "Dell XPS 15 (2020) retired for parts.", "tag": "END-OF-LIFE", "time": "4 hours ago", "type": "danger"},
        ],
        "portfolios": [
            {"name": "Microsoft 365 Enterprise", "description": "Standard Enterprise Suite", "value": "1,200 seats allocated", "accent": "dark"},
            {"name": "Slack Business+", "description": "Messaging & Collab", "value": "840", "accent": "green"},
            {"name": "Adobe Creative Cloud", "description": "Creative Suite", "value": "142", "accent": "red"},
        ],
        "page_invoices": "Invoices",
        "invoices_description": "Digital curation of fiscal assets and expenditure verification.",
        "btn_new_invoice": "New Invoice",
        "label_nf_number": "NF Number",
        "label_supplier": "Supplier",
        "label_date": "Date",
        "label_value": "Value",
        "label_files": "Files",
        "form_manual_entry": "Manual Entry",
        "form_manual_entry_description": "Enter fiscal data precisely as issued.",
        "form_nf_number": "NF Number",
        "form_series": "Series",
        "form_supplier": "Supplier",
        "form_cnpj": "Supplier CNPJ",
        "form_date": "Date",
        "form_total_value": "Total Value",
        "form_drop_label": "Drop PDF or XML here",
        "form_drop_note": "Maximum file size: 10MB",
        "btn_finalize_record": "Finalize Record",
        "label_monthly_cap": "Monthly Cap",
        "label_validated": "Validated",
        "page_licenses": "Software License Inventory",
        "licenses_description": "Software license control and strategic compliance.",
        "search_licenses": "Search licenses...",
        "btn_filters": "Filters",
        "label_expiring_next_30_days": "Expiring Next 30 Days",
        "label_healthy_status": "Healthy Status",
        "label_software_asset": "Software Asset",
        "label_license_type": "License Type",
        "label_allocation": "Allocation",
        "label_expiration": "Expiration",
        "label_status": "Status",
        "label_license_key": "License Key / Secret",
        "label_purchase_reference": "Purchase Reference",
        "label_asset_owner": "Asset Owner",
        "label_audit_interval": "Audit Interval",
        "label_lifecycle_actions": "Lifecycle Actions",
        "btn_renew_license": "Renew License",
        "btn_export_compliance": "Export Compliance PDF",
        "btn_revoke_access": "Revoke Access",
        "page_machines": "Machines Control",
        "metric_total_assets": "Total Assets",
        "metric_active_now": "Active Now",
        "metric_avg_health": "Avg. Health",
        "table_workstation_identity": "Workstation Identity",
        "table_current_user": "Current User",
        "table_department": "Department",
        "table_status": "Status",
        "software_installed": "Installed Software",
        "linked_licenses": "Linked Licenses",
        "license_id": "License ID",
        "renewal_date": "Renewal",
        "profile_title": "Profile",
        "profile_subtitle": "View and manage your account details.",
        "label_username": "Username",
        "label_name": "Name",
        "label_email": "Email",
        "label_date_joined": "Joined",
        "reset_password_title": "Forgot Password",
        "reset_password_subtitle": "Enter your email to reset your password.",
        "reset_password_email_label": "Email",
        "reset_password_button": "Send reset link",
        "reset_password_back_login": "Back to login",
        "new_password_title": "Create a new password",
        "new_password_subtitle": "Set your new password and then login.",
        "new_password_label": "New password",
        "new_password_confirm_label": "Confirm new password",
        "new_password_button": "Save new password",
        "modal_new_invoice_title": "New Invoice",
        "modal_cnpj_label": "Supplier CNPJ",
        "modal_supplier_label": "Supplier",
        "modal_nf_number_label": "Invoice Number",
        "modal_series_label": "Series",
        "modal_date_label": "Date",
        "modal_value_label": "Total Value",
        "modal_attachment_label": "Attach PDF or XML",
        "modal_save_button": "Save Invoice",
        "modal_cancel_button": "Cancel",
    },
    "pt": {
        "nav_dashboard": "Painel",
        "nav_invoices": "Notas Fiscais",
        "nav_licenses": "Licenças",
        "nav_machines": "Máquinas",
        "nav_profile": "Perfil",
        "btn_new_asset": "Novo Ativo",
        "btn_settings": "Configurações",
        "btn_support": "Suporte",
        "search_placeholder": "Pesquisar...",
        "lang_toggle": "English",
        "dashboard_title": "Visão Estratégica",
        "dashboard_subtitle": "Inventário global de TI e status de conformidade.",
        "btn_generate_report": "Gerar Relatório",
        "btn_export_csv": "Exportar CSV",
        "card_total_assets": "Total de Ativos",
        "card_active_licenses": "Licenças Ativas",
        "card_monthly_spend": "Gasto Mensal",
        "section_critical_alerts": "Alertas Críticos",
        "section_software_utilization": "Utilização de Software por Setor",
        "section_recent_history": "Histórico de Movimentações",
        "view_all": "Ver tudo",
        "alerts": [
            {
                "title": "Risco de Conformidade de Licença",
                "description": "Licenças do Adobe Creative Cloud excedidas. 142 máquinas detectadas vs 120 assentos alocados. Possível passivo de auditoria: $3.200.",
                "label": "2 problemas detectados",
                "type": "critical",
            },
            {
                "title": "Contratos de Software a Vencer",
                "description": "Renovação do JetBrains Enterprise em 14 dias. Custo estimado: $12.450.",
                "label": "Revisar Nota",
                "type": "warning",
            },
        ],
        "history": [
            {"title": "MacBook Pro M3 Provisionado", "subtitle": "Atribuído para: Sara Chen (Engenharia)", "tag": "TAG DO ATIVO AM-4320", "time": "14 min atrás", "type": "success"},
            {"title": "Realocação de Licença", "subtitle": "Suite AutoCAD movida de Marketing para o pool de P&D.", "tag": "SOFT-ATIVO", "time": "1 hora atrás", "type": "info"},
            {"title": "Hardware Descomissionado", "subtitle": "Dell XPS 15 (2020) aposentado para peças.", "tag": "FIM-DE-VIDA", "time": "4 horas atrás", "type": "danger"},
        ],
        "portfolios": [
            {"name": "Microsoft 365 Enterprise", "description": "Standard Enterprise Suite", "value": "1,200 assentos alocados", "accent": "dark"},
            {"name": "Slack Business+", "description": "Messaging & Collab", "value": "840", "accent": "green"},
            {"name": "Adobe Creative Cloud", "description": "Creative Suite", "value": "142", "accent": "red"},
        ],
        "page_invoices": "Notas Fiscais",
        "invoices_description": "Curadoria digital de ativos fiscais e verificação de despesas.",
        "btn_new_invoice": "Nova Nota",
        "label_nf_number": "Número NF",
        "label_supplier": "Fornecedor",
        "label_date": "Data",
        "label_value": "Valor",
        "label_files": "Arquivos",
        "form_manual_entry": "Entrada Manual",
        "form_manual_entry_description": "Digite os dados fiscais exatamente como emitidos.",
        "form_nf_number": "Número NF",
        "form_series": "Série",
        "form_supplier": "Fornecedor",
        "form_cnpj": "CNPJ",
        "form_date": "Data",
        "form_total_value": "Valor Total",
        "form_drop_label": "Solte PDF ou XML aqui",
        "form_drop_note": "Tamanho máximo do arquivo: 10MB",
        "btn_finalize_record": "Finalizar Registro",
        "label_monthly_cap": "Teto Mensal",
        "label_validated": "Validado",
        "page_licenses": "Inventário de Licenças de Software",
        "licenses_description": "Controle de licenças de software e conformidade estratégica.",
        "search_licenses": "Pesquisar licenças...",
        "btn_filters": "Filtros",
        "label_expiring_next_30_days": "Vencendo nos Próximos 30 Dias",
        "label_healthy_status": "Status Saudável",
        "label_software_asset": "Ativo de Software",
        "label_license_type": "Tipo de Licença",
        "label_allocation": "Alocação",
        "label_expiration": "Expiração",
        "label_status": "Status",
        "label_license_key": "Chave de Licença / Segredo",
        "label_purchase_reference": "Referência de Compra",
        "label_asset_owner": "Proprietário do Ativo",
        "label_audit_interval": "Intervalo de Auditoria",
        "label_lifecycle_actions": "Ações de Ciclo de Vida",
        "btn_renew_license": "Renovar Licença",
        "btn_export_compliance": "Exportar PDF de Conformidade",
        "btn_revoke_access": "Revogar Acesso",
        "page_machines": "Controle de Máquinas",
        "metric_total_assets": "Total de Ativos",
        "metric_active_now": "Ativos Agora",
        "metric_avg_health": "Saúde Média",
        "table_workstation_identity": "Identidade da Estação de Trabalho",
        "table_current_user": "Usuário Atual",
        "table_department": "Departamento",
        "table_status": "Status",
        "software_installed": "Software Instalado",
        "linked_licenses": "Licenças Vinculadas",
        "license_id": "ID da Licença",
        "renewal_date": "Renovação",
        "profile_title": "Perfil",
        "profile_subtitle": "Veja e gerencie os dados da sua conta.",
        "label_username": "Usuário",
        "label_name": "Nome",
        "label_email": "E-mail",
        "label_date_joined": "Criado em",
        "reset_password_title": "Esqueceu a senha",
        "reset_password_subtitle": "Digite seu e-mail para redefinir sua senha.",
        "reset_password_email_label": "E-mail",
        "reset_password_button": "Enviar link de redefinição",
        "reset_password_back_login": "Voltar ao login",
        "new_password_title": "Criar nova senha",
        "new_password_subtitle": "Defina sua nova senha e faça login.",
        "new_password_label": "Nova senha",
        "new_password_confirm_label": "Confirmar nova senha",
        "new_password_button": "Salvar nova senha",
        "modal_new_invoice_title": "Nova Nota Fiscal",
        "modal_cnpj_label": "CNPJ do Fornecedor",
        "modal_supplier_label": "Fornecedor",
        "modal_nf_number_label": "Número NF",
        "modal_series_label": "Série",
        "modal_date_label": "Data",
        "modal_value_label": "Valor Total",
        "modal_attachment_label": "Anexar PDF ou XML",
        "modal_save_button": "Salvar Nota",
        "modal_cancel_button": "Cancelar",
    },
}

# Dashboard mock data
DASHBOARD_STATS = [
    {"label": "card_total_assets", "value": "1,520", "change": "+8%", "icon": "inventory_2"},
    {"label": "card_active_licenses", "value": "932", "change": "+5%", "icon": "verified"},
    {"label": "card_monthly_spend", "value": "$48,300", "change": "-2%", "icon": "paid"},
]

# Invoices mock data
INVOICES_RECORDS = [
    {"number": "#NF-902341", "supplier": "DataStream Systems", "date": "Oct 12, 2024", "value": "$12,450.00"},
    {"number": "#NF-882109", "supplier": "CloudScale Infra", "date": "Oct 08, 2024", "value": "$4,820.50"},
    {"number": "#NF-876551", "supplier": "Vertex Security", "date": "Sep 28, 2024", "value": "$2,100.00"},
    {"number": "#NF-854123", "supplier": "Core Net Tech", "date": "Sep 15, 2024", "value": "$18,900.00"},
]

# Licenses mock data
LICENSES_SUMMARY = [
    {"title": "card_total_assets", "value": "482", "accent": "primary"},
    {"title": "label_healthy_status", "value": "94%", "accent": "secondary"},
    {"title": "label_expiring_next_30_days", "value": "12 Licenses", "accent": "dark"},
]

LICENSES_ITEMS = [
    {"name": "Windows 11 Enterprise", "type": "License Type", "usage": "215 / 250", "expires": "Oct 14, 2025", "status": "ACTIVE"},
    {"name": "Office 365 Business Premium", "type": "License Type", "usage": "105 / 100", "expires": "Nov 22, 2024", "status": "OVER-LIMIT"},
    {"name": "Adobe Creative Cloud", "type": "License Type", "usage": "12 / 15", "expires": "Dec 01, 2023", "status": "EXPIRED"},
    {"name": "Slack Enterprise Grid", "type": "License Type", "usage": "450 / 500", "expires": "May 10, 2025", "status": "ACTIVE"},
]

# Machines mock data
MACHINES_METRICS = [
    {"label": "metric_total_assets", "value": "128"},
    {"label": "metric_active_now", "value": "94"},
    {"label": "metric_avg_health", "value": "98%"},
]

MACHINES_LIST = [
    {"id": "WS-PRD-4029", "model": "Dell Precision 5820", "user": "Elena Rodriguez", "department": "Engineering", "status": "active"},
    {"id": "MBP-DSG-011", "model": "MacBook Pro M2", "user": "Marcus Thorne", "department": "Design", "status": "active"},
    {"id": "WS-FIN-992", "model": "HP Z6 G4 Tower", "user": "Sarah Jenkins", "department": "Finance", "status": "offline"},
    {"id": "WS-PRD-102", "model": "Dell Latitude 7420", "user": "Arthur Dent", "department": "Operations", "status": "active"},
    {"id": "MBP-EXE-001", "model": "MacBook Pro 16'", "user": "Thomas Shelby", "department": "Executive", "status": "active"},
]